version "3.6"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    platform: linux/x86_64
    ports:
      - "3306:3306"
    volumes:
      - mysql-data-volume:/var/lib/mysql
      - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    restart: always
    environment:
      MYSQL_USER: xuemi
      MYSQL_PASSWORD: xuemi_example
      MYSQL_ROOT_PASSWORD: xuemi_example

volumes:
  mysql-data-volume: